// <auto-generated />
using System;
using Handbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Handbook.Data.Migrations
{
    [DbContext(typeof(HandbookContext))]
    [Migration("20220321102409_FixedData")]
    partial class FixedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Handbook.Data.Models.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff1e53d3-2a2e-408e-87d7-d9730eaba1f1"),
                            ProductPrice = 3.14m
                        },
                        new
                        {
                            Id = new Guid("0a28b823-9cd0-463a-bd6b-5214418df4eb"),
                            ProductPrice = 2.14m
                        },
                        new
                        {
                            Id = new Guid("b0489e52-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 4m
                        },
                        new
                        {
                            Id = new Guid("c0489e52-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 9.13m
                        },
                        new
                        {
                            Id = new Guid("a0489e52-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 8.62m
                        },
                        new
                        {
                            Id = new Guid("c0286e52-f38c-4756-1a1d-301ea97465c4"),
                            ProductPrice = 7.91m
                        },
                        new
                        {
                            Id = new Guid("c0183e12-f48c-4656-3f1d-301ea97465c4"),
                            ProductPrice = 39.1m
                        },
                        new
                        {
                            Id = new Guid("1b715737-6b1b-481d-98c4-4f9f950b77c9"),
                            ProductPrice = 2.99m
                        },
                        new
                        {
                            Id = new Guid("f3ea7b4b-2124-47a3-9f7c-019b49b548bb"),
                            ProductPrice = 5.99m
                        },
                        new
                        {
                            Id = new Guid("a5132f31-c38c-4756-9f1d-331ea97465c4"),
                            ProductPrice = 6.4m
                        },
                        new
                        {
                            Id = new Guid("a1251a31-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 7.99m
                        },
                        new
                        {
                            Id = new Guid("a4146e31-f38c-4756-9f1d-341ea97465c4"),
                            ProductPrice = 8.99m
                        },
                        new
                        {
                            Id = new Guid("d1221e52-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 9.99m
                        },
                        new
                        {
                            Id = new Guid("c6162a51-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            Id = new Guid("c7851e31-a52c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 10.99m
                        },
                        new
                        {
                            Id = new Guid("c0412d32-a38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 11.99m
                        },
                        new
                        {
                            Id = new Guid("d2352e75-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 12.99m
                        },
                        new
                        {
                            Id = new Guid("a2316f61-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 13.99m
                        },
                        new
                        {
                            Id = new Guid("f6814e52-f38c-4756-9f1d-301ea97465c4"),
                            ProductPrice = 14.99m
                        },
                        new
                        {
                            Id = new Guid("f9419e52-f38c-4352-9d2d-301ea97465c4"),
                            ProductPrice = 15.99m
                        },
                        new
                        {
                            Id = new Guid("f9419e52-f38c-4352-9d2d-301ea92571c4"),
                            ProductPrice = 16.99m
                        },
                        new
                        {
                            Id = new Guid("f9419e52-f38c-4352-9d2d-301ea46165f1"),
                            ProductPrice = 17.99m
                        },
                        new
                        {
                            Id = new Guid("f3429e52-f81c-3352-9d2d-301ea97465c4"),
                            ProductPrice = 8.22m
                        },
                        new
                        {
                            Id = new Guid("41080b38-5ae9-4f07-9c7b-bd058fc0e778"),
                            ProductPrice = 9.22m
                        },
                        new
                        {
                            Id = new Guid("f9419e52-f23c-4342-9f2d-311ea57765c4"),
                            ProductPrice = 10.22m
                        },
                        new
                        {
                            Id = new Guid("f1412e52-f64c-4321-9a2d-301ea97465c4"),
                            ProductPrice = 11.22m
                        },
                        new
                        {
                            Id = new Guid("4e9f1871-aacb-4934-a94a-21ad576e11cc"),
                            ProductPrice = 12.22m
                        },
                        new
                        {
                            Id = new Guid("c6429f52-f61c-4352-9a2d-301ea97465c4"),
                            ProductPrice = 13.22m
                        },
                        new
                        {
                            Id = new Guid("d6321f52-f61c-4452-9f2d-301fa97435c4"),
                            ProductPrice = 14.22m
                        },
                        new
                        {
                            Id = new Guid("d6321f52-f61c-4452-9f2d-406fa29645c4"),
                            ProductPrice = 15.22m
                        },
                        new
                        {
                            Id = new Guid("d6321f52-f61c-7153-9f2d-229fa97435c4"),
                            ProductPrice = 16.22m
                        },
                        new
                        {
                            Id = new Guid("d8392f52-f61c-9382-9f2d-221fa97435c4"),
                            ProductPrice = 17.22m
                        },
                        new
                        {
                            Id = new Guid("d6321f52-f61c-3927-9f2d-812fa93725c4"),
                            ProductPrice = 18.22m
                        },
                        new
                        {
                            Id = new Guid("eca5ffe7-134c-401a-b0a9-d3fb08d4bf0f"),
                            ProductPrice = 3.01m
                        });
                });

            modelBuilder.Entity("Handbook.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChanges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a1cb0f8-19c9-4d43-a8d7-5590346ca3f2"),
                            BarCode = "PC-1-CC",
                            Code = 0,
                            Color = "Red",
                            DateChanges = new DateTime(2022, 3, 21, 13, 24, 8, 517, DateTimeKind.Local).AddTicks(5365),
                            Model = "Sugar",
                            Name = "Coca-cola",
                            PriceId = new Guid("ff1e53d3-2a2e-408e-87d7-d9730eaba1f1"),
                            Quantity = 1m,
                            Size = "1 1",
                            Sort = "Drink",
                            Weight = "1"
                        });
                });

            modelBuilder.Entity("Handbook.Data.Models.Product", b =>
                {
                    b.HasOne("Handbook.Data.Models.Price", "Price")
                        .WithMany("Products")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Handbook.Data.Models.Price", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
